#### Import NumPy

In [2]:
import numpy as np
from numpy import random

#### Create an array of 10 zeros

In [3]:
np.full(10,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [4]:
np.repeat(1,10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [5]:
# arr=np.array([1,2,3])
# print(type(arr))
# h=arr.view()
# print(h)
# print(type(h))
a=np.full(10,5)
print(a)


[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50 -!del!-

In [6]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50  -!del!-

In [7]:
a1=np.arange(10,51,2)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
b1=np.arange(0,9)
b1.resize(3,3)
print(b1)
np.info(b1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x218ef204f80
byteorder:  little
byteswap:  False
type: int32


#### Create a 3x3 identity matrix

In [9]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [10]:
np.random.random(1)

array([0.36404647])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
n=random.normal(size=(25)).reshape(5,5)
print(n)

[[ 0.57778894 -0.2573713   0.87539302 -2.79521176  0.16261644]
 [-0.02993475 -0.92276351  0.47401776  0.56946772  0.36615819]
 [-1.7835062  -0.87525589 -1.79665153  0.13282591 -0.39271321]
 [ 1.17539772  1.56063966 -0.57411929 -0.40458395 -0.30000858]
 [-0.00699582 -1.23365889 -0.46510466 -0.70777202  0.66580449]]


#### Create the following matrix: -!del!-

In [12]:
c=np.linspace(0.01,1.0,num=100).reshape(10,10)
print(c)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
d=np.linspace(0.0,1.0,num=22)
print(d)

[0.         0.04761905 0.0952381  0.14285714 0.19047619 0.23809524
 0.28571429 0.33333333 0.38095238 0.42857143 0.47619048 0.52380952
 0.57142857 0.61904762 0.66666667 0.71428571 0.76190476 0.80952381
 0.85714286 0.9047619  0.95238095 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [14]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [16]:
print(mat[2:,1:])


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [17]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [18]:
print(20)

20


In [19]:
print(mat[3][4])
print(mat[3,4])

20
20


In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
print(mat[:3,1])

[ 2  7 12]


In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
print(mat[4])

[21 22 23 24 25]


In [24]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

### Now do the following

#### Get the sum of all the values in mat

In [25]:
sum=mat.sum()
print(sum)

325


#### Get the standard deviation of the values in mat

In [26]:
print(mat.std())

7.211102550927978


#### Get the sum of all the columns in mat

In [27]:

l=mat.transpose()
ls=np.array([])
for i in l:
    ls=np.append(ls,i.sum())
print(ls)
print(np.sum(mat,axis=0))


[55. 60. 65. 70. 75.]
[55 60 65 70 75]


#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [28]:
A=[[1,2],[3,4]]
B=[[4,5],[6,7]]
C=np.matmul(A,B)
print(C)

[[16 19]
 [36 43]]


####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [32]:
nan=np.nan
k=np.array([[1.3,2.5,3.6,nan],[2.6,3.3,nan,5.5],[2.1,3.2,5.4,6.5]])
avg = np.nanmean(k,axis=0)
nan_loc = np.isnan(k)
k[nan_loc] = np.take(avg, np.where(nan_loc)[True])
print(k)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


# You're done!